version: "3"

services:
  # Hadoop services
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      # - hadoop_namenode:/hadoop/dfs/name
      - /home/xingzheng/Distributed-Operator/docker/data/hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=testmake
    env_file:
      - ./storage/hadoop.env
    ports:
      - 50070:50070
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.2

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      # - hadoop_datanode:/hadoop/dfs/data
      - /home/xingzheng/Distributed-Operator/docker/data/hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./storage/hadoop.env
    ports:
      - 50075:50075
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.3

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./storage/hadoop.env
    ports:
      - 8088:8088
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.4

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./storage/hadoop.env
    ports:
      - 8042:8042
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.5

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      # - hadoop_historyserver:/hadoop/yarn/timeline
      - /home/xingzheng/Distributed-Operator/docker/data/hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./storage/hadoop.env
    ports:
      - 8188:8188
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.6

  # Hbase cluster
  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.7
    

  hbase-master:
    image: danxing/hbase-standalone:1.0.1-hbase2.0.0
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./storage/hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16000:16000
      - 16010:16010
    command: /opt/hbase-2.0.0/bin/hbase master start
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.8

  hbase-region:
    image: danxing/hbase-standalone:1.0.1-hbase2.0.0
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./storage/hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-regionserver
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16020:16020
      - 16030:16030
    command: /opt/hbase-2.0.0/bin/hbase regionserver start
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.9

  jobmanager:
    image: danxing/flink:1.10.2-scala_2.12
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - zoo:zookeeper
      - hbase-master
      - hbase-region:hbase-regionserver
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.10
    volumes:
      - /home/xingzheng/Distributed-Operator/output/jobmanager:/home

  taskmanager:
    image: danxing/flink:1.10.2-scala_2.12
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - zoo:zookeeper
      - hbase-master
      - hbase-region:hbase-regionserver
    networks:
      flinkHbase: 
        ipv4_address: 172.27.0.11
    volumes:
      - /home/xingzheng/Distributed-Operator/output/taskmanager:/home
  


networks:
   flinkHbase:
      ipam:
         config:
         - subnet: 172.27.0.0/16
