version: "3.9"
services:
  jobmanager:
    image: flink:1.12.0-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 1G
        reservations:
          cpus: 0.05
          memory: 500M


  taskmanager:
    image: flink:1.12.0-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 4
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 1G
        reservations:
          cpus: 0.05
          memory: 500M
